site_name: BearCart Documentation
site_url: https://UCAEngineeringPhysics.github.io/BearCart
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  # - API Reference: api.md

theme:
  name: readthedocs
